"""Validation reason codes.

P0 spec §37 examples are included even when the related catalog does not
exist yet. Do not invent success by mapping unknown data to a fallback.
"""

from __future__ import annotations

VALID = "VALID"
INVALID = "INVALID"

INVALID_ID = "INVALID_ID"
UNKNOWN_ENTITY_TYPE = "UNKNOWN_ENTITY_TYPE"
AMBIGUOUS_ENTITY_TYPE = "AMBIGUOUS_ENTITY_TYPE"
ID_DERIVED_FROM_DISPLAY_NAME = "ID_DERIVED_FROM_DISPLAY_NAME"
DUPLICATE_ID = "DUPLICATE_ID"

UNKNOWN_ATTRIBUTE = "UNKNOWN_ATTRIBUTE"
INVALID_ATTRIBUTE_BOUNDS = "INVALID_ATTRIBUTE_BOUNDS"
INVALID_ATTRIBUTE_VALUE = "INVALID_ATTRIBUTE_VALUE"
INSUFFICIENT_ATTRIBUTE = "INSUFFICIENT_ATTRIBUTE"
NEGATIVE_AMOUNT = "NEGATIVE_AMOUNT"
NEGATIVE_DELTA_TIME = "NEGATIVE_DELTA_TIME"

UNKNOWN_EVENT_TYPE = "UNKNOWN_EVENT_TYPE"
INVALID_PAYLOAD = "INVALID_PAYLOAD"
MISSING_FIELD = "MISSING_FIELD"
INVALID_DATA_FILE = "INVALID_DATA_FILE"

# Reserved from P0 spec §37 — used when those catalogs exist.
UNKNOWN_PRIMITIVE = "UNKNOWN_PRIMITIVE"
UNKNOWN_ATTACK = "UNKNOWN_ATTACK"
UNKNOWN_WEAPON = "UNKNOWN_WEAPON"
INVALID_SEQUENCE = "INVALID_SEQUENCE"
NEGATIVE_DURATION = "NEGATIVE_DURATION"
INVALID_STAMINA_COST = "INVALID_STAMINA_COST"
MISSING_WEAPON_REQUIREMENT = "MISSING_WEAPON_REQUIREMENT"
