"""Canonical event types.

P0 spec §29 is the required combat bus set.
PRIMITIVE_INTERRUPTED comes from §14.3.
DODGE_SUCCESS / DODGE_FAILURE come from §23.
"""

from __future__ import annotations

INPUT_ACTION = "INPUT_ACTION"
MOVEMENT_STARTED = "MOVEMENT_STARTED"
MOVEMENT_STOPPED = "MOVEMENT_STOPPED"
PRIMITIVE_STARTED = "PRIMITIVE_STARTED"
PRIMITIVE_COMPLETED = "PRIMITIVE_COMPLETED"
PRIMITIVE_INTERRUPTED = "PRIMITIVE_INTERRUPTED"
ATTACK_STARTED = "ATTACK_STARTED"
ATTACK_ACTIVE = "ATTACK_ACTIVE"
ATTACK_HIT = "ATTACK_HIT"
ATTACK_MISSED = "ATTACK_MISSED"
DODGE_STARTED = "DODGE_STARTED"
DODGE_COMPLETED = "DODGE_COMPLETED"
DODGE_SUCCESS = "DODGE_SUCCESS"
DODGE_FAILURE = "DODGE_FAILURE"
BLOCK_STARTED = "BLOCK_STARTED"
BLOCK_HIT = "BLOCK_HIT"
PARRY_STARTED = "PARRY_STARTED"
PARRY_SUCCESS = "PARRY_SUCCESS"
PARRY_FAILURE = "PARRY_FAILURE"
DAMAGE_APPLIED = "DAMAGE_APPLIED"
ENTITY_DIED = "ENTITY_DIED"
STAMINA_CHANGED = "STAMINA_CHANGED"

REQUIRED_BUS_EVENTS = frozenset(
    {
        INPUT_ACTION,
        MOVEMENT_STARTED,
        MOVEMENT_STOPPED,
        PRIMITIVE_STARTED,
        PRIMITIVE_COMPLETED,
        ATTACK_STARTED,
        ATTACK_ACTIVE,
        ATTACK_HIT,
        ATTACK_MISSED,
        DODGE_STARTED,
        DODGE_COMPLETED,
        BLOCK_STARTED,
        BLOCK_HIT,
        PARRY_STARTED,
        PARRY_SUCCESS,
        PARRY_FAILURE,
        DAMAGE_APPLIED,
        ENTITY_DIED,
        STAMINA_CHANGED,
    }
)

KNOWN_EVENT_TYPES = REQUIRED_BUS_EVENTS | {
    PRIMITIVE_INTERRUPTED,
    DODGE_SUCCESS,
    DODGE_FAILURE,
}
